// AUTOGENERATED FILE; DO NOT EDIT 

import com.acmerobotics.dashboard.config.Config; 
import org.firstinspires.ftc.teamcodekt.components.scheduler.auto.AutoProvider; 

@Config 
public class AutoProvideImpl implements AutoProvider { 
    @Override 
    public void scheduleAuto() { 
        ActualAutoBuilder builder = new ActualAutoBuilder() 
            .forward(forward0$distance) 
            .turn(turn0$angle) 
            .splineTo(splineTo0$x, splineTo0$y, splineTo0$heading) 
            .temporalMarker(temporalMarker0$offset, temporalMarker0$callback; 
    } 

    public static double forward0$distance = 3.937007874015748;
    public static double turn0$angle = 1.5707963267948966;
    public static double splineTo0$x = 3.937007874015748;
    public static double splineTo0$y = 3.937007874015748;
    public static double splineTo0$heading = 0.0;
    public static double temporalMarker0$offset = 0.5;
    public static com.acmerobotics.roadrunner.trajectory.MarkerCallback temporalMarker0$callback; 
    { 
        try (ObjectInput oi = new ObjectInputStream(new FileInputStream("C:\\Users\\wanna\\AppData\\Local\\Temp\\autobuilder_temporalMarker5439366554730952376ser"))) { 
            temporalMarker0$callback = (com.acmerobotics.roadrunner.trajectory.MarkerCallback) oi.readObject(); 
        } 
    } 
} 
