// AUTOGENERATED FILE; DO NOT EDIT

package org.firstinspires.ftc.teamcode.opmodes.RogueBaseAuto;

import androidx.annotation.NonNull;

import com.acmerobotics.dashboard.config.Config;

import org.firstinspires.ftc.teamcode.roadrunner.drive.SampleMecanumDrive;
import org.firstinspires.ftc.teamcodekt.components.scheduler.auto.AutoProvider;
import org.firstinspires.ftc.teamcodekt.components.scheduler.auto.ActualAutoBuilder;

import java.io.IOException;
import java.io.ObjectInput;
import java.io.FileInputStream;
import java.io.ObjectInputStream;

@Config
public class AutoProviderImpl implements AutoProvider {
    @Override
    public void scheduleAuto(@NonNull SampleMecanumDrive drive) {
        ActualAutoBuilder builder = new ActualAutoBuilder(drive)
            .forward(forward0$distance) 
            .turn(turn0$angle) 
            .splineTo(splineTo0$x, splineTo0$y, splineTo0$heading) 
            .temporalMarker(temporalMarker0$offset, temporalMarker0$callback) 
            .forward(forward1$distance) 
            .temporalMarker(temporalMarker1$offset, temporalMarker1$callback) 
            .forward(forward2$distance) 
            .temporalMarker(temporalMarker2$offset, temporalMarker2$callback) 
            .forward(forward3$distance) 
            .temporalMarker(temporalMarker3$offset, temporalMarker3$callback); 
    } 

    public static double forward0$distance = 10.0;

    public static double turn0$angle = 90.0;

    public static double splineTo0$x = 10.0;

    public static double splineTo0$y = 10.0;

    public static double splineTo0$heading = 0.0;

    public static double temporalMarker0$offset = 0.5;

    private static com.acmerobotics.roadrunner.trajectory.MarkerCallback temporalMarker0$callback; 
    static { 
        try (ObjectInput oi = new ObjectInputStream(new FileInputStream("C:\\Users\\wanna\\AppData\\Local\\Temp\\autobuilder_temporalMarker13537295576468947363ser"))) { 
            temporalMarker0$callback = (com.acmerobotics.roadrunner.trajectory.MarkerCallback) oi.readObject(); 
        } catch (IOException | ClassNotFoundException e) { 
            e.printStackTrace(); 
        } 
    } 

    public static double forward1$distance = 10.0;

    public static double temporalMarker1$offset = 0.0;

    private static com.acmerobotics.roadrunner.trajectory.MarkerCallback temporalMarker1$callback; 
    static { 
        try (ObjectInput oi = new ObjectInputStream(new FileInputStream("C:\\Users\\wanna\\AppData\\Local\\Temp\\autobuilder_temporalMarker6559342085970339335ser"))) { 
            temporalMarker1$callback = (com.acmerobotics.roadrunner.trajectory.MarkerCallback) oi.readObject(); 
        } catch (IOException | ClassNotFoundException e) { 
            e.printStackTrace(); 
        } 
    } 

    public static double forward2$distance = 10.0;

    public static double temporalMarker2$offset = 0.0;

    private static com.acmerobotics.roadrunner.trajectory.MarkerCallback temporalMarker2$callback; 
    static { 
        try (ObjectInput oi = new ObjectInputStream(new FileInputStream("C:\\Users\\wanna\\AppData\\Local\\Temp\\autobuilder_temporalMarker15382719210621046668ser"))) { 
            temporalMarker2$callback = (com.acmerobotics.roadrunner.trajectory.MarkerCallback) oi.readObject(); 
        } catch (IOException | ClassNotFoundException e) { 
            e.printStackTrace(); 
        } 
    } 

    public static double forward3$distance = 10.0;

    public static double temporalMarker3$offset = 0.0;

    private static com.acmerobotics.roadrunner.trajectory.MarkerCallback temporalMarker3$callback; 
    static { 
        try (ObjectInput oi = new ObjectInputStream(new FileInputStream("C:\\Users\\wanna\\AppData\\Local\\Temp\\autobuilder_temporalMarker15724625874487357021ser"))) { 
            temporalMarker3$callback = (com.acmerobotics.roadrunner.trajectory.MarkerCallback) oi.readObject(); 
        } catch (IOException | ClassNotFoundException e) { 
            e.printStackTrace(); 
        } 
    } 
} 
